# Generated by Django 5.2.4 on 2025-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_bio_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('banner_image', models.ImageField(upload_to='category_banners/')),
                ('link', models.CharField(blank=True, help_text='Add #CategoryName or a URL', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Season Sale Men’s & Women’s Fashion', max_length=100)),
                ('subtitle', models.CharField(default='Shop the latest trends in technology, accessories, and fashion with exclusive discounts up to 70% off!', max_length=200)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('hero_image', models.ImageField(upload_to='hero_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
