# Generated by Django 5.2.4 on 2025-11-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categorybanner_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryBanner',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
